### ISSUE TITLE
`git clone` throwing errors.

### ISSUE THREAD

**Issue by RaphaelIT7** [Source-Authors/obsolete-source-engine#1]
If you run `git clone https://github.com/Source-Authors/obsolete-source-engine.git --recurse-submodules`
You get a bunch of errors like this:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Source-Authors/SDL.git' into submodule path '[Path]/obsolete-source-engine/thirdparty/SDL' failed
Failed to clone 'thirdparty/SDL'. Retry scheduled
Cloning into '[Path]/obsolete-source-engine/thirdparty/bzip2'...
Host key verification failed.
fatal: Could not read from remote repository.
```

This is because the modules have the wrong url.
Example:
```
[submodule "ivp"]
	path = ivp
	url = git@github.com:Source-Authors/source-physics.git
```
It should be like this:
```
[submodule "ivp"]
	path = ivp
	url = https://github.com/Source-Authors/source-physics.git
```

**Comment by dimhotepus** [comment]
> If you run `git clone https://github.com/Source-Authors/obsolete-source-engine.git --recurse-submodules` You get a bunch of errors like this:
> 
> ```
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:Source-Authors/SDL.git' into submodule path '[Path]/obsolete-source-engine/thirdparty/SDL' failed
> Failed to clone 'thirdparty/SDL'. Retry scheduled
> Cloning into '[Path]/obsolete-source-engine/thirdparty/bzip2'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> ```
> 
> This is because the modules have the wrong url. Example:
> 
> ```
> [submodule "ivp"]
> 	path = ivp
> 	url = git@github.com:Source-Authors/source-physics.git
> ```
> 
> It should be like this:
> 
> ```
> [submodule "ivp"]
> 	path = ivp
> 	url = https://github.com/Source-Authors/source-physics.git
> ```

Yep, that's because you use `https` to clone repo, but submodules are using `ssh` protocol.

I suggest to setup SSH key to access github repositories. See https://github.com/settings/keys and follow links for SSH.

Also it may be useful to add SSH key when you open bash on Windows: https://towardsaws.com/add-github-ssh-agent-and-ssh-key-on-startup-windows-9276c697a693

**Comment by RaphaelIT7** [comment]
I'm gonna try it.

I'm also having some problems with compiled version. What files are exactly needed?
I got all hl2 files, but it throws me an error:
![image](https://github.com/Source-Authors/obsolete-source-engine/assets/64648134/48f010d9-7f9d-408f-ac46-a637340f9407)

**Comment by dimhotepus** [comment]
> I'm gonna try it.
> 
> I'm also having some problems with the compiled version. What files are exactly needed? I got all hl2 files, but it throws me an error: ![image](https://user-images.githubusercontent.com/64648134/270008386-48f010d9-7f9d-408f-ac46-a637340f9407.png)
> 
> Edit: Tested it with TF2 and it seems to work but after starting a game it still throws an error: ![image](https://user-images.githubusercontent.com/64648134/270031008-8d46edc7-3034-4a71-87a6-9fa2a6b4f6dc.png)

Those are asserts for DEBUG version. You can ignore them (Ignore All Asserts).

Valve updated dx level 90 shaders for hl2 / episodic / ep2, so you need to use `-dxlevel 80` as a launch option.

**Comment by RaphaelIT7** [comment]
Everything works for me now, Thanks :D
